---
- hosts: raspberry
  vars:
    influxdb_version: 1.2.2
    influxdb_password: hous3inth3country
    grafana_version: 4.2.0
    ruby_version: 2.4.1
  remote_user: pi
  become_user: root
  become: true
  tasks:

  ## Basic Setup ##
  - name: Install base packages
    apt: name={{ item }} state=latest
    with_items:
      - vim
      - unattended-upgrades
      - apt-listchanges
      - htop
  - name: install bash aliases
    template:
      src: config/bash_aliases
      dest: /home/pi/.bash_aliases
      owner: pi
      group: pi

  ## Playbooks ##
  - include: playbooks/influxdb_playbook.yml
  - include: playbooks/grafana_playbook.yml
  - include: playbooks/ruby_playbook.yml
    become_user: pi
    become: true

  handlers:
    - name: restart influxdb
      command: /etc/init.d/influxdb restart

