---
- name: Check grafana version number
  command: bash -c "if [ -f /usr/sbin/grafana-cli ]; then grafana-cli --version || grep {{ grafana_version }}; fi"
  register: current_grafana_version
- name: Install dependencies
  apt: name={{ item }} state=latest
  with_items:
    - adduser
    - libfontconfig
- name: Download and install grafana
  command: "{{ item }}"
  with_items:
    - wget https://github.com/fg2it/grafana-on-raspberry/releases/download/v{{ grafana_version }}/grafana_{{ grafana_version }}_armhf.deb -O /tmp/grafana_{{ grafana_version }}_armhf.deb
    - dpkg -i /tmp/grafana_{{ grafana_version }}_armhf.deb
    - rm /tmp/grafana_{{ grafana_version }}_armhf.deb
    - update-rc.d grafana-server defaults
    - update-rc.d grafana-server enable
    - service grafana-server start
  when: current_grafana_version.stdout.find('Grafana') == -1
